/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Forms;

/**
 *
 * @author yaroslavb
 */
public class LosePanel extends javax.swing.JPanel {

    /**
     * Creates new form LosePanel
     */
    public LosePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelGameOver = new javax.swing.JLabel();
        LabelLose = new javax.swing.JLabel();
        ButtonPlayAgain = new javax.swing.JButton();
        ButtonQuit = new javax.swing.JButton();

        LabelGameOver.setFont(new java.awt.Font("Impact", 0, 48)); // NOI18N
        LabelGameOver.setText("GAME OVER");

        LabelLose.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        LabelLose.setForeground(new java.awt.Color(234, 41, 41));
        LabelLose.setText("You lose");

        ButtonPlayAgain.setBackground(new java.awt.Color(137, 87, 64));
        ButtonPlayAgain.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        ButtonPlayAgain.setText("Play again");

        ButtonQuit.setBackground(new java.awt.Color(137, 87, 64));
        ButtonQuit.setFont(new java.awt.Font("Impact", 0, 14)); // NOI18N
        ButtonQuit.setText("Quit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelGameOver)
                .addGap(155, 155, 155))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(LabelLose, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ButtonQuit, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ButtonPlayAgain))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(LabelGameOver, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelLose)
                .addGap(8, 8, 8)
                .addComponent(ButtonPlayAgain)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ButtonQuit)
                .addContainerGap(122, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonPlayAgain;
    private javax.swing.JButton ButtonQuit;
    private javax.swing.JLabel LabelGameOver;
    private javax.swing.JLabel LabelLose;
    // End of variables declaration//GEN-END:variables
}
